# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.provision "shell", path: "puppet-bootstrap-centos.sh" 
  config.vm.provision "shell", path: "puppet-modules.sh"
  config.vm.provision "puppet" 

  config.vm.provider "aws" do |aws, override|
    config.vm.box = "dummy"
    aws.access_key_id =     ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name =      ENV['AWS_KEYPAIR_NAME']

    aws.ami = "ami-785bae10"
    aws.instance_type = "m3.large"

    aws.tags = { 'Name' => 'LibraryCloud API / Search'}
    aws.security_groups = [ 'vagrant' ]
    override.ssh.username = "ec2-user"
    config.ssh.pty = true
    override.ssh.private_key_path = ENV['AWS_PRIVATE_AWS_SSH_KEY_PATH']
  end


end
